---
- name: Setup Vprofile Bastion Host
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC setup Variable
      include_vars: vars/bastion_setup.txt

    - name: Import VPC Setup Variable
      include_vars: vars/vpc_setup.txt
