- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: create a VPC with dedicated tenancy and request an IPv6 CIDR
      ec2_vpc_net:
        name: Module_dev2
        cidr_block: 10.10.0.0/16
        ipv6_cidr: True
        region: us-east-1
        tenancy: dedicated